#!/bin/bash
### BEGIN INIT INFO
# Provides:             moloch 
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         
# Short-Description:    moloch 
### END INIT INFO

case "$1" in
  start)
    su cuckoo -c "cd /data/moloch/bin/ && ./run_es.sh"
    sleep 15
    su cuckoo -c "cd /data/moloch/bin/ && screen -d -m ./run_viewer.sh"
    su cuckoo -c "cd /data/moloch/bin/ && screen -d -m ./run_wise.sh"
;;
  stop)
    pkill -f "elasticsearch-"
    pkill -f "viewer.js"
    pkill -f "run_wise.sh" 
;;

 restart)
   $0 stop
   sleep 10
   $0 start
   ;;

esac
exit 0

